# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/contrs.xdc

# Block Designs: bd/zynq_1/zynq_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1 || ORIG_REF_NAME==zynq_1}]

# IP: bd/zynq_1/ip/zynq_1_processing_system7_1_0/zynq_1_processing_system7_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_processing_system7_1_0 || ORIG_REF_NAME==zynq_1_processing_system7_1_0}]

# IP: bd/zynq_1/ip/zynq_1_proc_sys_reset_1_0/zynq_1_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_proc_sys_reset_1_0 || ORIG_REF_NAME==zynq_1_proc_sys_reset_1_0}]

# IP: bd/zynq_1/ip/zynq_1_processing_system7_1_axi_periph_0/zynq_1_processing_system7_1_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_processing_system7_1_axi_periph_0 || ORIG_REF_NAME==zynq_1_processing_system7_1_axi_periph_0}]

# IP: bd/zynq_1/ip/zynq_1_axi_gpio_0_0/zynq_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_axi_gpio_0_0 || ORIG_REF_NAME==zynq_1_axi_gpio_0_0}]

# IP: bd/zynq_1/ip/zynq_1_auto_pc_2/zynq_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_1_auto_pc_2 || ORIG_REF_NAME==zynq_1_auto_pc_2}]

# XDC: bd/zynq_1/ip/zynq_1_processing_system7_1_0/zynq_1_processing_system7_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_1_processing_system7_1_0 || ORIG_REF_NAME==zynq_1_processing_system7_1_0}] {/inst }]/inst ]]

# XDC: bd/zynq_1/ip/zynq_1_proc_sys_reset_1_0/zynq_1_proc_sys_reset_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_1_proc_sys_reset_1_0 || ORIG_REF_NAME==zynq_1_proc_sys_reset_1_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_1/ip/zynq_1_proc_sys_reset_1_0/zynq_1_proc_sys_reset_1_0_ooc.xdc

# XDC: bd/zynq_1/ip/zynq_1_proc_sys_reset_1_0/zynq_1_proc_sys_reset_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_1_proc_sys_reset_1_0 || ORIG_REF_NAME==zynq_1_proc_sys_reset_1_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_1/ip/zynq_1_axi_gpio_0_0/zynq_1_axi_gpio_0_0_ooc.xdc

# XDC: bd/zynq_1/ip/zynq_1_axi_gpio_0_0/zynq_1_axi_gpio_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_1_axi_gpio_0_0 || ORIG_REF_NAME==zynq_1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_1/ip/zynq_1_axi_gpio_0_0/zynq_1_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_1_axi_gpio_0_0 || ORIG_REF_NAME==zynq_1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_1/ip/zynq_1_auto_pc_2/zynq_1_auto_pc_2_ooc.xdc

# XDC: bd/zynq_1/zynq_1_ooc.xdc
